model: debug
server:
  ip: 127.0.0.1
  port: 3011
  name: cmp_service
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: Cmsops@2025
  db_name: cmp_service
  charset: utf8mb4
  conn_max_lifetime: 60
  max_idle_conns: 10
  max_open_conns: 100
  disable_foreign_key_constraint_when_migrating: true
